=== AECgeeks/ifc-pipeline-validation/application/checks/ids.xsd
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Leon van Berlo (Overleaf Investments B.V.) -->
<!-- DRAFT - NOT FOR PRODUCTION -->
<xs:schema xmlns:ids="http://standards.buildingsmart.org/IDS" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://standards.buildingsmart.org/IDS" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.2">
	<xs:element name="ids">
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ids:idsType">
					<xs:sequence>
						<xs:element name="info">
							<xs:complexType>
								<xs:choice>
									<xs:element name="ifcversion"/>
									<xs:element name="description" minOccurs="0"/>
									<xs:element name="author" minOccurs="0"/>
									<xs:element name="copyright"/>
									<xs:element name="version"/>
									<xs:element name="date" type="xs:date"/>
									<xs:element name="purpose" minOccurs="0"/>
									<xs:element name="milestone" minOccurs="0"/>
								</xs:choice>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="entityType">
		<xs:sequence>
			<xs:element name="name" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can only be entities from the IFC schema for which the IDS is created. Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="predefinedtype" type="xs:anyType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Can only be predefined types from the IFC schema for which the IDS is created. Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="classificationType">
		<xs:sequence>
			<xs:element name="value" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)
</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="system" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="applicabilityType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="entity" type="ids:entityType"/>
			<xs:element name="classification" type="ids:classificationType" minOccurs="0"/>
			<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:propertyType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="material" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:materialType"/>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="systemType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="href" type="xs:anyURI" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="propertyType">
		<xs:sequence>
			<xs:element name="propertyset" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="name" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="value" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace) </xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="materialType">
		<xs:sequence>
			<xs:element name="value" type="xs:anyType">
				<xs:annotation>
					<xs:documentation>Can have (multiple) XSD Restrictions/Facets (enumeration, fractionDigits, length, maxExclusive, maxInclusive, maxLength, minExclusive, minInclusive, minLength, pattern, totalDigits, whiteSpace)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="location" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="type"/>
					<xs:enumeration value="instance"/>
					<xs:enumeration value="any"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="requirementsType">
		<xs:choice maxOccurs="unbounded">
			<xs:element name="entity" type="ids:entityType" minOccurs="0"/>
			<xs:element name="classification" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:classificationType">
							<xs:sequence>
								<xs:element name="instructions" type="xs:string" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="property" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:propertyType">
							<xs:sequence>
								<xs:element name="instructions" type="xs:string" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="href" type="xs:string" use="optional"/>
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="material" minOccurs="0">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="ids:materialType">
							<xs:sequence>
								<xs:element name="instructions" type="xs:string" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Author of the IDS can leave instructions for the authors of the IFC. This text could/should be displayed in the BIM/IFC authoring tool.</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="use" use="optional">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="required"/>
										<xs:enumeration value="optional"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="href" type="xs:string"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="specificationType">
		<xs:sequence>
			<xs:element name="applicability" type="ids:applicabilityType"/>
			<xs:element name="requirements" type="ids:requirementsType"/>
		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="idsType">
		<xs:sequence>
			<xs:element name="specification" type="ids:specificationType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== AECgeeks/ifc-pipeline-validation/application/checks/IDS_example-without-restrictions.xml
<?xml version="1.0" encoding="UTF-8"?>
<ids xmlns="http://standards.buildingsmart.org/IDS" xsi:schemaLocation="http://standards.buildingsmart.org/IDS http://standards.buildingsmart.org/IDS/ids.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<specification name="binder">
		<applicability>
			<entity>
				<name>IfcCovering</name>
				<predefinedtype>CLADDING</predefinedtype>
			</entity>
			<classification location="instance">
				<value>21.22</value>
				<system>NL-Sfb</system>
			</classification>
		</applicability>
		<requirements>
			<entity>
				<name>IfcCovering</name>
				<predefinedtype>CLADDING</predefinedtype>
			</entity>
			<classification location="type">
				<value>whatever</value>
				<system href="http://identifier.buildingsmart.org/uri/owner/name">NL-Sfb</system>
			</classification>
			<property location="instance" href="http://identifier.buildingsmart.org/uri/buildingsmart/ifc-4.3/prop/FireRating">
				<propertyset>AedesUVIP</propertyset>
				<name>Firerating</name>
				<value>whatever</value>
				<instructions>Please add the desired fire rating</instructions>
			</property>
			<property location="type" href="https://identifier.buildingsmart.org/uri/something">
				<propertyset>Anas</propertyset>
				<name>Codice WBS</name>
				<value>whatever</value>
			</property>
			<material location="type" href="https://identifier.buildingsmart.org/uri/something" use="optional">
				<value>whatever</value>
				<instructions>The only acceptable value is one lowercase letter (from a to z)</instructions>
			</material>
		</requirements>
	</specification>
	<r/>
</ids>
